### ISSUE TITLE
Feature Request: use custom console implementation

### ISSUE THREAD

**Issue by iiroj** [listr2/listr2#651]
For [lint-staged](https://github.com/okonet/lint-staged), I would like the possibility of supplying a custom `console` implementation, to be used for the `simple` and `verbose` loggers (probably not the `default`, since the use-case probably is not relevant with TTY renderers).

This is mainly so that _lint-staged_'s Node.js API can fully capture all logs when using it like `await lintStaged({ logger: myCustomLogger })` (here `logger` defaults to `global.console`). Currently it will capture all task output (like ESLint errors), but leave out the _Listr_ output because the renderers use directly either `console` methods or the `process.stdout.write`.

It would also be useful for tests, I guess...

I could also take a stab at creating a PR for this. Initially I though I'd just add a new option to the `Logger` class so that it can be supplied a `options.console` parameter, but looks like the renderers are not implemented in the same way. My initial idea/draft is something like this:

1. add support for `new Logger({ console: myCustomConsole })`
1. add support for passing the logger `options` _without_ also using a custom `logger` (so use the default logger with options). Currently it looks like you need both for the `verbose` renderer: https://github.com/cenk1cenk2/listr2/blob/a554689c5e7b21f7781c183ab0bfba46cbd27545/src/renderer/verbose.renderer.ts#L54
1. add support for the `logger` in the `simple ` renderer as well. I was thinking that it could use a discriminated type to accept either the `output` or `logger` options, but not both at the same time. When given a `logger`, it would use that instead of directly writing to `process.stdout`
1. while we're at it, slightly improve the types for the `logger` option so that its arguments are not `any` type.

What do you think?

**Comment by cenk1cenk2** [comment]
Hey @iiroj ,

Nice to talk with you again.

I am actually up for this kind of change as you have suggested.

In order:
1. This can easily be added to put your custom implementation or logic, in between where you can process the data further before sending it to the console.
2. I suppose, I have not added this since the usual logger does not need any options.
3. Again this would be very nice because there is no standard between different renderers and this simple renderer came in with a pull request. It would not need much in the sense of having prefixes etc. but maybe it can be converted to look a bit more like the verbose renderer to have some kind of a structure between renderers.
4. A generic type should serve fine in this case and would be an easy fix.

So it would make a perfect addition.

But to be honest, I do not have enough time these days (which I thought it would only be like this for a couple of weeks in the beginning) and again honestly and realistically until the end of the summer to implement this.

So yeah even though, I will get back to closing the issues and implementing the changes that I wanted to make for a couple of years now, sadly I would not be able to allocate much time for this until my situation changes.

Please do inform me whether you would like to implement this on your behalf because I also do need to move the CI setup to somewhere else for it to properly build a new version.

**Comment by cenk1cenk2** [comment]
Please checkout the beta version to see if you have any comments on it.

You can check out the related logger section [here](https://listr2.kilic.dev/renderer/logger.html) and common process output section [here](https://listr2.kilic.dev/renderer/process-output.html).

Now all renderers use the same logger to output to stdout/stderr so you can capture anything in between. I suppose your case can be solved by passing a custom implementation of ProcessOutput to the ListrLogger.

This is currently available through beta but I will finalize this soon.
