### ISSUE TITLE
Can't use Enquirer Select or other choice based

### ISSUE THREAD

**Issue by mcgear** [listr2/listr2#662]
I am trying to use Listr2 with Enquirer Select prompt.  When doing this, all previous command lines are removed, and only some options are provided.

Other prompt types work, but the choices seem to blow up Listr

**Comment by mcgear** [comment]
Some clarity, i discovered that i can actually scroll the list, however, the UI is malformed for the first item in the list:

The list is there if i hold "down":
![image](https://user-images.githubusercontent.com/1460046/214353105-f18010b3-be79-462a-862d-735ecc4c9e15.png)

However if i scroll back up, selector disappears:
![image](https://user-images.githubusercontent.com/1460046/214353225-ffc4d9f0-2709-434e-984f-588930af73d1.png)

And you can see in both examples that the first item is always messed up
![image](https://user-images.githubusercontent.com/1460046/214353355-86327bfa-22fa-44bf-b114-d31dd6e5df98.png)
![image](https://user-images.githubusercontent.com/1460046/214353379-311155e7-e084-49e7-bd2d-1a3360aa86e0.png)
![image](https://user-images.githubusercontent.com/1460046/214353435-1176e082-84f5-4e1f-a5b4-2cf7c9c2967c.png)

We can also see that the previous listr tasks have disappeared until i select from the list:
![image](https://user-images.githubusercontent.com/1460046/214353615-9b954b52-908e-4244-bb40-df1d51a354c7.png)
![image](https://user-images.githubusercontent.com/1460046/214353705-e322c790-e1f3-440d-9dbf-c8e5b785ede0.png)

How do we get the select to work more inline like input and other types?  I would believe this would also cause some issue with other enquirer custom types

**Comment by cenk1cenk2** [comment]
Thank you for the detailed report @mcgear.

Unfortunately, I can not reproduce this with my current setup on Linux and Kitty terminal, do you think this could be a terminal shell-caused problem since how this internally works is through swallowing clear line unicode characters from Enquirer to not clear the whole line?

https://github.com/cenk1cenk2/listr2/blob/7b443f9c24a48963c9a95b7545f6792b4474a143/src/lib/task-wrapper.ts#L101

If you can fix this locally on your environment, I would happily merge it.

**Comment by cenk1cenk2** [comment]
Closing as stale, since I can not reproduce, maybe beta would be an improvement for you but not guaranteed.
