### ISSUE TITLE
[Feature]: Support of Inquirer

### ISSUE THREAD

**Issue by xaviermonin** [listr2/listr2#676]
### Feature Request

Hello,

Enquirer has not been maintained for several years now. Would it be possible to use Inquirer instead, or to allow it to be used as an alternative?

### Contribution

- [ ] I can implement this feature without anything else required, when specification finalizes.
- [ ] I can implement this feature with guidence.
- [X] It is just a request.

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been added already.

**Comment by cenk1cenk2** [comment]
Hello @xaviermonin,

Yeah that would be possible but I am not sure when I will get to it. Just have to check of it feasible with the current structure since the clear line ANSI chars are hacked out from the prompts to not make the default renderer break.

The main reason I did not select it as the prompt engine in the initial implementation was it was pretty slow and had huge set of dependencies. But as an optional peer dependency it should be okay since it is not bundled with the application.

I completely agree that eventhough mostly enquirer works it is not maintainted it could use at least some dependency updates.

**Comment by tommy-mitchell** [comment]
> The main reason I did not select it as the prompt engine in the initial implementation was it was pretty slow and had huge set of dependencies.

FWIW, the new `@inquirer/prompts` is much smaller ([new](https://packagephobia.com/result?p=@inquirer/prompts@3.0.4) vs [old](https://packagephobia.com/result?p=inquirer@9.2.10)): https://github.com/SBoudrias/Inquirer.js/discussions/1214

**Comment by tommy-mitchell** [comment]
Great :) btw, the new Inquirer is written in TypeScript, so you can map the types instead of re-writing them like with Enquirer:

```ts
import type * as Inquirer from '@inquirer/prompts'

type Prompts =
  | typeof Inquirer.input
  | typeof Inquirer.select
  | typeof Inquirer.checkbox
  | typeof Inquirer.confirm
  | typeof Inquirer.password
  | typeof Inquirer.expand
  | typeof Inquirer.editor
  | typeof Inquirer.rawlist

type PromptOptions<PromptType extends Prompts> = Parameters<PromptType>[0]

type InputPromptOptions = PromptOptions<typeof Inquirer.input>

type SelectPromptOptions = PromptOptions<typeof Inquirer.select>

type CheckboxPromptOptions = PromptOptions<typeof Inquirer.checkbox>

type ConfirmPromptOptions = PromptOptions<typeof Inquirer.confirm>

type PasswordPromptOptions = PromptOptions<typeof Inquirer.password>

type ExpandPromptOptions = PromptOptions<typeof Inquirer.expand>

type EditorPromptOptions = PromptOptions<typeof Inquirer.editor>

type RawListPromptOptions = PromptOptions<typeof Inquirer.rawlist>
```

**Comment by cenk1cenk2** [comment]
Dear @tommy-mitchell,

I have implemented an adapter-based approach to support both `enquirer` and `inquirer` which breaks the current behavior but since I was also doing some breaking changes for other issues.

Please check out the latest `v7.0.0-beta.3` release to see if this will work in your case.

The new documentation for prompts can be found [here](https://listr2.kilic.dev/task/prompts.html) and mentioned in the brief migration guide for `v7` on the documentation website.

Keep in mind that since this is `beta`, it is not final and if you have any input, I would be glad to discuss further.
