### ISSUE TITLE
[Support]: Query/Inspect data in ProcessOutputBuffer

### ISSUE THREAD

**Issue by rushi** [listr2/listr2#677]
### Support Request

Hi, I'm working on yet another tool using listr2 and have a couple of questions regarding the stdout, stderr handling by listr2. I've read the [docs](https://listr2.kilic.dev/renderer/process-output.html), but haven't understood it clear enough to solve the problem.

I have multiple tasks that dump MongoDB data from a remote server and the output of the dump command contains the progress information of the data being dumped. This is what the output looks like:

```
2023-05-13T23:13:40.350+0530 writing cms.users to dump/cms/users.bson
2023-05-13T23:13:40.722+0530[........................]  cms.users  0/20030855  (0.0%)
2023-05-13T23:13:43.721+0530[........................]  cms.users  101/20030855  (0.0%)
2023-05-13T23:13:46.718+0530[........................]  cms.users  7739/20030855  (0.0%)
2023-05-13T23:13:49.718+0530[........................]  cms.users  22577/20030855  (0.1%)
2023-05-13T23:13:52.717+0530[........................]  cms.users  36652/20030855  (0.2%)
2023-05-13T23:13:55.718+0530[........................]  cms.users  52389/20030855  (0.3%)
2023-05-13T23:13:58.718+0530[........................]  cms.users  52389/20030855  (0.3%)
```

I'd like to some how be able to read the information stored in the [temporary buffer](https://listr2.kilic.dev/renderer/process-output.html#hijack) so I can just do `task.output = Completed: 0.3%;` or something to report the progress to the user.

Also if the app prints an error it would be easy for me to detect that and fail the task.

I am using the default render (since it's cleaner) and v6.4.2. Please let me know if you can help, or if you have any pointers. 

Thanks,

Rushi

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).

**Comment by cenk1cenk2** [comment]
Hello @rushi,

This is an exciting use-case, but I find it very cool to do so.

ProcessOutput is only intended for renderers and to hook the `process.stdout` and `process.stderr` temporarily while rendering to not break how the `log-update` behaves, so it does not entirely fit this use case.

Even though you can use `ProcessOutputBuffer` as temporary storage to hold some string data inside of it, I realized I did not make it a `ReadableStream` so it can not be accessed through `message` events and writing them to `task.output`.

But we can use `WritableStream`s as `process.stdout` or `process.stderr`, and I usually just dump the whole output of a command to the `task.output`, but realized that I had no example for it in the documentation.

With a new version I have exposed the very basic of creating a temporary `WriteStream` the way I use for prompts and `task.stdout()`.

I have added both examples, which is the case I use most, just dumping every output, and another one which I think will fit your case perfectly fine.

You can find them under, https://listr2.kilic.dev/task/output.html#render-output-of-a-command , a couple of minutes after this issue is closed and new documentation is published.

**Comment by rushi** [comment]
@cenk1cenk2 You are absolutely **amazing** You have solved my problem so quickly and by explaining it so well. Doing a release and updating documentation on top of that is an extra bonus. 

Thank you very much! ♥️

**Comment by cenk1cenk2** [comment]
No worries, you can reopen the issue if it does not fit your use case.
