### ISSUE TITLE
[Support]: How do i signal that root task is failed after returning newListr with a list of subtasks?

### ISSUE THREAD

**Issue by gutnikov-joom** [listr2/listr2#680]
### Support Request

Hello! I need some guidance on how to improve a particular aspect of the application I'm working on. I'm currently facing some difficulties with managing a task tree, which looks something like this:

```
TaskA
   |_ TaskB
   |_ TaskC
```

In the application I'm building, TaskA not only spawns two subtasks (TaskB and TaskC), but it also performs some additional operations that might potentially fail. When such an error occurs, I need to be able to signal this failure so that Listr can update TaskA's status accordingly.

This is what I'm currently doing:

```
// Defining function for TaskA:
const taskFn: ListrTaskFn = (ctx, wrapper) => {
  // Call an asynchronous handler when work is completed
  doSomeWork((err) => {
    if (err) {
        wrapper.report(new Error('Oh no'), ListrErrorTypes.HAS_FAILED);
    }
  });

  // Also create two subtasks: TaskB and TaskC
  return wrapper.newListr([
    {
      // Definition of TaskB goes here
    },
    {
      // Definition of TaskC goes here
    },
  ]);
};

const taskA = {
  title: 'TaskA', 
  task: taskFn
}
```

But unfortunately this doesn't mark TaskA as an errored. So i wonder is there any way to do that? 
I'd appreciate any tips or recommendations. Thank you!

**Comment by cenk1cenk2** [comment]
Hello @gutnikov-joom,

I do not think I understand the question clearly, but do you want to fail the parent task of TaskA from either of the subtasks TaskB and TaskC?

If you throw an error before TaskB and TaskC are created TaskA would fail without spawning those subtasks so that should be handled, if you can just `throw new Error()` before returning the subtasks. If you do want to fail the parent task from the subtasks, I did not think of that while structuring this, if any of the subtasks would fail, the parent should be marked as failed too.

Thank you for the example, if you can help me understand a bit more, it would be very nice since I am failing to do so.

**Comment by gutnikov-joom** [comment]
Wow, thanks to the quick response! 
Ok, so here is the thing. In my case, TaskA does not only return two subtasks, but also performs some extra work ( asynchronous ). So i was wondering if there is there is any way to fail task A asynchronousely ( see code below )

```
  const root = new Listr({
    title: "TaskA",
    task: (ctx, wrapper) => {
    
      // Some asynchronous logic that can potentially fail, so i wonder if i can mark taskA as failed from here?
      setTimeout(() => {
        wrapper.report(new Error("Failed"), ListrErrorTypes.HAS_FAILED);
      }, 3000);

      // TaskA spawns two subtasks
      return wrapper.newListr([
        {
          title: "TaskB",
          task: () =>
            new Promise((resolve) => {
              setTimeout(resolve, 10000);
            }),
        },
        {
          title: "TaskC",
          task: () =>
            new Promise((resolve) => {
              setTimeout(resolve, 15000);
            }),
        },
      ]);
    },
  });

  try {
    await root.run({});
  } catch (err) {
    console.log(err);
  }
```

I understand that probably this example doesn't make a lot of sense, but i simplified a code to get rid of useless details

**Comment by cenk1cenk2** [comment]
Hmm I do not think this is possible by design. If you had especially awaited the parent task I would say yes this would work. 

Give throwing an error a try instead of calling the report function but if it works it is not the fully intended behavior. 

But when it goes in to the subtask mode whenever you return a new listr from that it only evalutes it whether the subtasks are succeeded or not.

I can only advise you to rethink the structure if possible.

**Comment by gutnikov-joom** [comment]
Yeah, i've expected that. Was asking just in case if i missed something from the docs. 
Thanks anyway!
