### ISSUE TITLE
[Bug]: Task run finished should return task return value 

### ISSUE THREAD

**Issue by tianyingchun** [listr2/listr2#682]
### Replication of the Problem

return task.run()  should correct return each task result data.

### Problem

return task.run()  should correct return each task result data.
```ts
  async run(context) {
    if (!this.renderer) {
      this.renderer = new this.rendererClass(this.tasks, this.rendererClassOptions, this.events);
    }
    await this.renderer.render();
    this.ctx = this.options?.ctx ?? context ?? {};
    await Promise.all(this.tasks.map((task) => task.check(this.ctx)));
    try {
// Maybe should be return?
      await Promise.all(this.tasks.map((task) => this.concurrency.add(() => this.runTask(task))));
      this.renderer.end();
    } catch (err) {
      if (this.options.exitOnError !== false) {
        this.renderer.end(err);
        throw err;
      }
    }
    return this.ctx;
  }
```

### Environment

 "listr2": "6.6.0",

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by cenk1cenk2** [comment]
I sincerely apologize for the late reply; it has slipped through my mind.

Please read the documentation about [context](https://listr2.kilic.dev/listr/context.html) where you can already use it to return values as defined in the example [here](https://listr2.kilic.dev/listr/context.html).

It is not the same thing but you can selectively return results from your tasks instead of replacing them all and accessing them through array indexes like `tasks[0][1]` for your first task and second subtask for example.

I can not break this behavior since this also comes from the original as well as being a core part of the operation.
