### ISSUE TITLE
[Bug]: `persistentOutput` with output streaming

### ISSUE THREAD

**Issue by tommy-mitchell** [listr2/listr2#683]
### Replication of the Problem

```js
import { Listr } from "listr2";
import { $ } from "execa";

const $$ = $({ shell: true });

const tasks = new Listr([{
	title: "echoes 1 2 3",
	task: async () => $$`echo 1 && sleep 1 && echo 2 && sleep 1 && echo 3`.stdout,
	options: {
		persistentOutput: true,
	},
}]);

await tasks.run();
```

### Problem

When streaming output with `persistentOutput: true`, new chunks/lines overwrite existing output. I'd expect each new line to append, rather than replace. Is this the intended behavior?

### Environment

<table>
<tr>
 <td>OS
 <td>MacOS 13.3.1
<tr>
 <td>Node.js
 <td>v18.16.1
<tr>
 <td>Terminal
 <td>iTerm2 3.4.19, zsh
<tr>
 <td>listr2
 <td>v6.6.1
</table>

### Log Output

Expected:

```sh
✔ echoes 1 2 3
  › 1
  › 2
  › 3
```

Actual:

```sh
✔ echoes 1 2 3
  › 3
```

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by cenk1cenk2** [comment]
hey @tommy-mitchell,

yes, indeed this is the intended behavior to just show the latest logs.
`persistentOutput` enables it to retain the last output for normal output.

You can also give a try to `bottomBar` option described [here](https://listr2.kilic.dev/task/output.html#defaultrenderer) since that is able to handle multiple lines, but it displays it after the tasks. Currently this same mechanism is not supported for normal data output since it usually breaks the rendering.
