### ISSUE TITLE
[Feature]: consider supporting the node14 version?

### ISSUE THREAD

**Issue by Max10240** [listr2/listr2#684]
### Feature Request

https://github.com/listr2/listr2/blob/260b7d31d6880257335a998553a65f7c8548cc67/src/utils/logger/logger.ts#L23-L25

But it(`??=`) wasn't supported until nodejs version 15.14: [link](https://node.green/#ES2021-features-Logical-Assignment-----basic-support)
Could we consider using this approach to avoid errors in earlier nodejs versions(although it seems less indirect and intuitive than before :(
```typescript
this.options.fields ?? (this.options.fields = {})
// ...
```

### Use Case

Works well in nodejs14 version

### Contribution

- [X] I can implement this feature without anything else required, when specification finalizes.
- [ ] I can implement this feature with guidence.
- [ ] It is just a request.

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been added already.

**Comment by Max10240** [comment]
or, just change `tsup>target` to es2020?
https://github.com/listr2/listr2/blob/260b7d31d6880257335a998553a65f7c8548cc67/tsup.config.ts#L11

**Comment by cenk1cenk2** [comment]
Hey @Max10240,

Sorry but unfortunately this is not something I can do since it will complicate staying compatible with all the underlying dependencies. It is common practice with other libraries too to drop unsupported versions of node and it would be hard to keep track of whether they actually support that older version or not even though I know that they currently do.

You can use the prior major version of this library which is `5` to use it in your older environment but I would highly recommend the update to latest supported LTS version of node.

**Comment by Max10240** [comment]
Ok, thanks for your reply and suggestions!

**Comment by cenk1cenk2** [comment]
No problem, sorry for inconvience.
