### ISSUE TITLE
[Feature]: Multiline output for DefaultRenderer

### ISSUE THREAD

**Issue by no2chem** [listr2/listr2#686]
### Feature Request

Currently, when `task.output` is called, `DefaultRenderer` is selected and `bottomBar` is set to false, only the latest `task.output` is rendered. For example, in:

```typescript
const tasks = new Listr(
  [
    {
      title: 'This task will execute.',
      task: async (ctx, task): Promise<void> => {
        task.output = 'I will push an output. [0]'
        await delay(500)

        task.output = 'I will push an output. [1]'
        await delay(500)

        task.output = 'I will push an output. [2]'
        await delay(500)
      }
    }
  ],
  { concurrent: false }
)

await tasks.run()
```

The output that would result would look something like:
```
  ✔ This task will execute
    › I will push an output. [2]
```

after execution
In some cases, it would be useful to verbosely log each output entry, resulting in:

```
  ✔ This task will execute
    › I will push an output. [0]
    › I will push an output. [1]
    › I will push an output. [2]
```

Potentially, this could be done by adding a multiline render option and having the DefaultRenderer store each output instead of discarding on each OUTPUT event from the task.

### Use Case

While the bottom bar is useful, it loses context as to what task it was performed under.

Being able to output multiple items under a single task would maintain the structure listr2 provides.

### Contribution

- [X] I can implement this feature without anything else required, when specification finalizes.
- [X] I can implement this feature with guidence.
- [ ] It is just a request.

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been added already.

**Comment by cenk1cenk2** [comment]
Dear @no2chem,

You are right since this is an option requested again lately on #683 maybe we can add this even though it might break the `log-update` if there is more output than the current terminal size.

This behavior is already implemented for bottom bar where it saves the prefered amount of lines for each task separately and cleans them up if it exceeds the preferred number of lines or the task is completed with `persistentOutput` set to `false`.

The same behavior can be implemented by accepting a boolean or a number where `false` would show no output, `true` will show all the output and the number can show the last given number of output through a renderer and renderer task option called something like `output`.

Currently, due to personal matters, I am not available but I will put this as high priority for the upcoming release. If you do want to implement this yourself and contribute with a pull request, you can also take a look at how the bottom bar is implemented in the default renderer. There should be another option to take in `output` just like the `bottomBar` for the renderer global option as well as the task itself. Then you can easily use the same buffering mechanism to buffer the output of the task and show it under the task directly.
