### ISSUE TITLE
[Bug]: SyntaxError: Unexpected token '??='

### ISSUE THREAD

**Issue by crazyair** [listr2/listr2#689]
### Replication of the Problem

```sh
➜   git:(master) gcam 'aa'
file:///Users/crazyair/Code/xxx/node_modules/.pnpm/listr2@6.6.1/node_modules/listr2/dist/index.js:206
    this.options.fields ??= {};
                        ^^^

SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:149:18)
husky - pre-commit hook exited with code 1 (error)
```

### Problem

this.options.fields ??= {};

### Environment

node: v16.19.1

### Log Output

```bash
SyntaxError: Unexpected token '??='
```

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by cenk1cenk2** [comment]
Dear @crazyair,

Please ensure that you are running the minimum supported version of node16. Maybe you do have multiple versions of node installed through `nvm`, `fnm`, or even your package manager. Husky might be running `sh` for your pre-commit process where it is skipping your environment variables through your node version manager if you are using any. You can verify that with going into `husky` hooks checking the shebang on top for which shell it is spawning, and running that shell and trying to do `node --version` there to be sure. 

But this should definitely be an environment problem.

You can check this operator from the compatibility matrix below.
https://node.green/#ES2020-features--nullish-coalescing-operator-----

Since node16 is the target for the minimum compatible version, this operator is not converted through the `esbuild` process.
