### ISSUE TITLE
[Support]: Is there a way to clear output per task?

### ISSUE THREAD

**Issue by tommy-mitchell** [listr2/listr2#703]
### Support Request

Can a task clear its own output? It can be controlled ahead of time via the `persistentOutput` option, but I want to clear the output if some condition is met:

```js
const tasks = new Listr([{
  title: 'foo',
  task: async (ctx, task) => {
    const someCondition = await thing();

    if (someCondition) {
      task.title = "Condition met!"
      task.clearOutput();
      return;
    }

    // do other stuff...
  },
  rendererOptions: {
    persistentOutput: true, // output persists by default
  },
}]);
```

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).

**Comment by cenk1cenk2** [comment]
Dear @tommy-mitchell,

Since I have offloaded output handling to the renderers themselves with one of the recent major versions, there is no easy way to do this. However, task can forward an event to the renderer to do that since there are mechanisms in place if this is supposed to be implemented.

You can try to drop the output of the task like `task.output = []` or `task.output = ''` but it might ignore them since they are empty and default renderer does not like empty outputs. This would only work in the case where there is only one output line outputted.

I do not think these days I have time to implement this, but it should be possible at least.

**Comment by tommy-mitchell** [comment]
Are these the events you're talking about?

https://github.com/listr2/listr2/blob/e41fc7cb06bdef2db222635e07bca6485abf7c60/packages/listr2/src/interfaces/listr-task-event-map.interface.ts#L14-L23

**Comment by cenk1cenk2** [comment]
Yes exactly and if it fires a certain event and renderer implements it, then it can clear output for that task. Because this is only valid in default renderer context.

**Comment by cenk1cenk2** [comment]
I would close this issue for cleanup reasons, if you want to pursue you can finalize the merge request.
