### ISSUE TITLE
[Bug]: Animation freezes when running external command (`execa`)

### ISSUE THREAD

**Issue by rrthomas** [listr2/listr2#715]
### Problem

When I run a sub-process as part of a listr2 task, the animation freezes. This did not happen with listr in the past.

Just checking that this is not expected before I try to construct a simple repro.

Thanks for listr2!

### Environment

Operating system: Ubuntu 22.04
Node.js version: 20.11.0
Terminal: Terminator
Listr2 version: 8.2.1

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by cenk1cenk2** [comment]
Dear @rrthomas,

Hello again,

I do not think this is intended because this also covers most of my use case with the library where it runs commands inside tasks. Can you open up a little more how do you encounter this?

**Comment by rrthomas** [comment]
Thanks for confirming that this should work! I shall see if I can find a simple reproducer, or maybe the process will lead me to a problem in my own code. Either way, I'll let you know.

**Comment by cenk1cenk2** [comment]
Hello @rrthomas,

I can replicate this behavior with the following example.

```typescript
import { execaSync } from 'execa'

import { Listr, delay } from 'listr2'

const tasks = new Listr(
  [
    {
      title: 'This task will execute.',
      task: (_, task): void => {
        const test = execaSync('sleep', [ '5s' ])

        task.output = test.stdout
      },
      rendererOptions: {
        persistentOutput: true
      }
    },

    {
      title: 'This task will execute.',
      task: async (): Promise<void> => {
        await delay(5000)
      },
      rendererOptions: {
        persistentOutput: true
      }
    }
  ],
  { concurrent: true }
)

await tasks.run()
```

These tasks running concurrently were supposed to finish at the same time so in 5 or so seconds in total. But since the first task is blocking the whole thread, it is finishing in 10 seconds. In the meantime `setInterval` which [updates the spinner](https://github.com/listr2/listr2/blob/master/packages/listr2/src/utils/ui/spinner.ts#L23) is not getting called at all.

![image](https://github.com/listr2/listr2/assets/26881592/c1d370e6-c41d-4d5f-81e8-6aac65d8533b)

I do think this is normal due to the nature of the language since it is blocking the whole thread, but not sure why would it behave differently in the original `Listr`, that might be due to I have migrated this project away from `rxjs` since it was a huge dependency.

I would guess that this behavior is not specific to `execa` because if we swap out `import { execaSync } from 'execa'
` with `import { spawnSync } from 'child_process'` due to its blocking nature it acts the same.

TBH, I have not thought this would be a problem while migrating away from `rxjs` to an `EventEmitter` based approach or what would be the difference causing this behavior.

I would close this issue since there is no easy way to fix it if I am not missing something and just would keep this in mind if there would be any other issues related to this.

**Comment by rrthomas** [comment]
Many thanks for looking into this. It makes perfect sense that a blocking call would block the spinner; I only reported it as an issue because it worked with Listr. As you say, it's a bit of a mystery how that ever worked!
